### ISSUE TITLE
bro theres nothing here

### ISSUE THREAD

**Issue by Roizor** [TFTWPhoenix/Ion-Lang#1]
i cant comple ion lang uage be cause not ing here

**Comment by TFTWPhoenix** [comment]
Umm look in the src folder...

**Comment by Roizor** [comment]
oh ok ill check

**Comment by Roizor** [comment]
yeah there is stuff but it wasnt there before lo

**Comment by TFTWPhoenix** [comment]
lol Ion-Lang is dead though...

**Comment by Roizor** [comment]
carb
